### ISSUE TITLE
Custom ntypescript compiler 

### ISSUE THREAD

**Issue by cstefan** [smrq/tsify#65] opened 2015-08-05 08:47 UTC
Tried the pass the ntypescript compiler in the options but I am getting an error.
Using it to write  jsx code in typerscript. That means the files have the extension .tsx.
Is this supported?

popup.tsx:2
import * as $ from 'jquery';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

Browserify config:
{
      entries: './Source/popup.tsx',
      dest: './Package',
      extensions: ['.tsx', '.ts'],
      outputName: 'popup.bundle.js',
      // list of externally available modules to exclude from the bundle
      external: libsArray
 }

Tsify plugin options:
.plugin('tsify', { 
			  	noImplicitAny: true,
				typescript: require("ntypescript"),
				declarationFiles: true,
				noExternalResolve: false,
				sortOutput: true,
				jsx: "react",
				module: 'commonjs'
			  })
Is there something wrong in the configuration?

**Comment by smrq** [comment] 2015-08-05 18:13
That error means that `popup.tsx` isn't being transformed before Browserify tries to bundle it. There's a known issue which can cause this (substack/node-browserify#1131, also discussed in #60) but from that config it doesn't look like this is the same case...  I can take a quick look, but a minimal repro would be helpful!

**Comment by smrq** [comment] 2015-08-06 17:15
Ah!  Nevermind, I know *exactly* what the problem is... I'll be fixing this.

**Comment by smrq** [comment] 2015-08-06 18:18
Should be fixed in 0.11.7

**Closed by smrq** 2015-08-06 18:18 UTC
