### ISSUE TITLE
Depend on typescript ~1.6.3 instead of ^1.6.3

### ISSUE THREAD

**Issue by vivainio** [smrq/tsify#78] opened 2015-09-19 18:56 UTC
Due to tsify, we had typescript 1.5 upgraded to 1.6 recently, which broke some builds (as 1.6 did some backwards incompatible changes).

It would be safer to keep each minor version of tsify locked to specific minor version of TS (e.g. 0.12.x to 1.6.x), so that you wouldn't get "surprise" typescript updates without updating tsify to next minor version.

Granted, this can be easily fixed by locking the typescript version in root package.json, but if this is the recommended fix it should be loudly documented somewhere.

**Comment by smrq** [comment] 2015-09-19 19:17
I'm a bit confused, because I did bump the minor version for TS 1.6? (I got
hit by the same thing on my own codebase, so I'm definitely aware of the
breaking change.)  If you were using ^0.11.0 then there should have been no
surprises.

Admittedly, the ramifications of semver would be clearer if I bumped to
1.0.0. It's about time, really.

**Comment by smrq** [comment] 2015-09-21 21:37
Ah, reading this again more closely, I see what you're saying the problem is.  Yeah, shame on Microsoft for breaking semver... I'll release 0.11.16 depending on typescript@~1.5.x, and 0.12.1 depending on typescript@~1.6.x

**Comment by smrq** [comment] 2015-09-21 21:41
Fixed in 0.11.16 and 0.12.1, for typescript@1.5 and 1.6, respectively.  Thanks for the report!

**Closed by smrq** 2015-09-21 21:41 UTC
