### ISSUE TITLE
Support External Require

### ISSUE THREAD

**Issue by giggio** [smrq/tsify#60] opened 2015-07-16 22:18 UTC
As defined in:
https://github.com/substack/node-browserify#external-requires

Using `.require(` as defined in https://github.com/substack/node-browserify#brequirefile-opts throws, it seems that the file is not being compiled before passed to browserify.

**Comment by johnnyreilly** [comment] 2015-07-17 08:47
I think I've just tripped up on the same issue.  I've got a project that uses Babel / Browserify at present.  I'm trying to migrate a few pieces over to TypeScript in a piecemeal fashion.  tsify seems to be doing just fine apart from when it comes to 3rd party typings.  Talk is cheap, show me the code.  

Here's an excerpt from the browerify + tsify gulp build step:

```js
  var src = './src/main.js';
  var dependencies = ['react', 'react-router', 'flux','events','babel/polyfill'];

  var appBundler = browserify({
    entries: [src],
    transform: [babelify.configure({ sourceMaps: false, stage: 3 })],
    debug: options.isDevelopment,
    cache: {}, packageCache: {}, fullPaths: options.isDevelopment
  })
  .external(dependencies)
  .plugin('tsify');
```

This works great apart from when it comes to require-ing 3rd party typings.  Consider the start of `fileWhichMakesTsifySad.ts`:

```
import * as ProtoBuf from 'protobufjs';
```

The above code requires the [protobufjs typing](https://github.com/borisyankov/DefinitelyTyped/blob/master/protobufjs/protobufjs.d.ts).  When using atom-typescript for text editing this is resolved quite happily using the typing specified in `typings/protobufjs/protobufjs.d.ts`.  However, when building with tsify the following error results:

> Error TS2307: Cannot find external module 'protobufjs'.

Is this an error in my usage of tsify?  Have I failed to point it to the correct place to find the typings?  I have a `tsconfig.json` which should do the job (I thought):

```
{
    "compileOnSave": false,
    "filesGlob": [
        "**/*.ts",
        "!node_modules/**/*.*"
    ],
    "version": "1.5.0-beta",
    "compilerOptions": {
        "target": "es5",
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true
    },
    "files": [
        "src/utils/fileWhichMakesTSIFYSad.ts",
        "typings/node/node.d.ts",
        "typings/protobufjs/protobufjs.d.ts"
    ]
}
```

In case it helps, I'm using tsd for pulling in typings from DefinitelyTyped and my `tsd.json` looks like this:

```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "protobufjs/protobufjs.d.ts": {
      "commit": "76e1dedf0bada455c0b75abeec3206d3aa5bd892"
    },
    "node/node.d.ts": {
      "commit": "76e1dedf0bada455c0b75abeec3206d3aa5bd892"
    }
  }
}
```

**Comment by johnnyreilly** [comment] 2015-07-20 10:11
I think (I'm not sure) that this problem might be related to [PR #32](https://github.com/smrq/tsify/pull/32).  The `declarationFiles` option that PR implements looks like it might allow for support of external typing files.  However, it doesn't look like that PR is going to be merged. :disappointed:

**Comment by smrq** [comment] 2015-07-20 16:02
@giggio Thanks for the report, I'll take a look.

@johnnyreilly Let me see if I get the dependency graph of your case:
```
main.js
  |--- fileWhichMakesTsifySad.ts
         |--- protobufjs
```
If that's the case, then all you're missing is to add `typings/tsd.d.ts` to `src` in your gulpfile.  Note that *tsify* cannot respect the `files` key in `tsconfig.json`, because it only compiles what Browserify gives to it.

**Comment by johnnyreilly** [comment] 2015-07-20 17:31
So `var src = './src/main.js';` becomes `var src = ['./src/main.js', 'typings/tsd.d.ts'];`? Thanks - I'll give it a try and report back!

**Comment by smrq** [comment] 2015-07-20 20:29
Reproduced... I think I'm going to have to delve into the guts of `module-deps` on this one.  Might be tricky!  I'll see how it goes.

**Comment by smrq** [comment] 2015-07-20 22:53
This appears to be a bug in `module-deps` which makes it think that the external file is a node built-in (like http, fs, etc.), which makes it bypass transforms.  Still looking into why that is happening.

**Comment by smrq** [comment] 2015-07-20 23:17
Okay, this is definitely a Browserify bug.  Exposing a file causes transforms not to run against it, unless the exposed name is different from the filename.  This is described in substack/node-browserify#1077, and further discussed in substack/node-browserify#1131.  A workaround would be to do something like:

```
b.require('./path/to/file.ts', { expose: 'some-other-name' })
```

If that won't work for you, then you can open an issue on Browserify and/or module-deps.

**Closed by smrq** 2015-07-20 23:17 UTC
Labels: bug

**Comment by johnnyreilly** [comment] 2015-07-21 13:01
Worked a dream once I updated to the latest version of tsify and the associated typings.  Thanks!

**Comment by twastvedt** [comment] 2015-09-01 17:53
@johnnyreilly As far as I can tell I have an issue similar to the one you described at the top of the thread. I'm not so sure about what I'm doing though, and in particular am not sure what to do with smrq's workaround. Where did you put that in your project? I want mine to work like a dream too!

**Comment by bcherny** [comment] 2016-07-28 20:57
If anyone is using browserify-shim and has this problem in the future, adding `global: true` fixed it for me:

```js
var browserify = require('browserify')

var files = ['./src/index.tsx', './src/other/index.ts']

browserify({
  entries: files,
  extension: ['js', 'ts', 'tsx'],
  external: ['angular', 'jquery', 'lodash', 'moment', 'react', 'react-dom', 'rx'],
  noParse: []
})
.plugin('tsify')
.transform('browserify-shim', {
  global: true
})
.bundle()
.on('error', error => console.error(error.toString()))
.on('log', msg => console.info(msg))
.pipe(process.stdout)
```

**Comment by frankkoenigstein** [comment] 2017-03-31 08:31
With the following karma.conf and specs I face some similar error:

```ts
const WATCH = process.argv.indexOf("--watch") > -1;

module.exports = (config) => {
    config.set({
        basePath: ".",
        browserify: {
            debug: true,
            extensions: [".js", ".ts"],
            plugin: ["tsify"]
        },
        files: [
            "test/karma-test-shim.ts",
            "test/**/*.spec.ts"
        ],
        frameworks: ["jasmine", "browserify"],
        mime: {
            "text/x-typescript": ["ts"]
        },
        phantomjsLauncher: {
            exitOnResourceError: true
        },
        port: 9876,
        preprocessors: {
            "test/**/karma-test-shim.ts": ["browserify"],
            "test/**/*.spec.ts": ["browserify"]
        },
        reporters: ["dots"],
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: WATCH,
        browsers: ["PhantomJS"],
        singleRun: !WATCH
    });
};

```

karma-test-shim.ts:
```ts
import { TestBed } from "@angular/core/testing";
import {
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting
} from "@angular/platform-browser-dynamic/testing";

TestBed.initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting()
);
```

test/some.spec.ts
```ts
describe("avlight", () => {
    it ("should run tests", () => {
        expect(true).toBe(true);
    });
});
```

```sh
31 03 2017 10:22:02.342:INFO [framework.browserify]: registering rebuild (autoWatch=true)
31 03 2017 10:22:06.313:ERROR [framework.browserify]: bundle error
31 03 2017 10:22:06.314:ERROR [framework.browserify]: 
/home/frank/git/someapp/test/karma-test-shim.ts:1
import { TestBed } from "@angular/core/testing";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
31 03 2017 10:22:06.316:WARN [karma]: No captured browser, open http://localhost:9876/
31 03 2017 10:22:06.322:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
31 03 2017 10:22:06.322:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
31 03 2017 10:22:06.333:INFO [launcher]: Starting browser PhantomJS
31 03 2017 10:22:06.618:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket DwjInIT4GuskAXmdAAAA with id 50553237
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: bundle error (see logs)
  at /tmp/8b9319764ff28d70be26c7f82b6f08ed.browserify:1
PhantomJS 2.1.1 (Linux 0.0.0): Executed 0 of 0 ERROR (0.073 secs / 0 secs)
```

Without `karma-test-shim.ts` => no import `some.spec.ts` is running. With `karma-test-shim.ts` browserify does not work.

Is that related to the described bug above? How can I fix that?

**Comment by cartant** [comment] 2017-03-31 09:22
What makes you think it's related to this particular issue? Yours is the only comment that mentions Karma. Is it the error message?

    ParseError: 'import' and 'export' may appear only with 'sourceType: module'

You'll see that whenever Browserify encounters ES6 content.

Could you please open a separate issue and include complete version information for the packages (Angular, Browserify, Tsify, etc.) that you are using?
